### ISSUE TITLE
Getters and Setters example 

### ISSUE THREAD

**Issue by mesfeir** [JanSeliv/SettingsWidgetConstructor#3]
Hi,

I am trying to assign getters and setters, but I can't seem to figure it out. I tried downloading the sample, but it doesn't show how to change these values in blueprint. I understand that you assign a class, and then a function from the class. what do you need to return from the function for it to be read from the getter/setter? what do you assign in the static class? the function only show up when I assign to a button, but even that doesn't trigger the function? Any help is much appreciated

**Comment by JanSeliv** [comment]
Hi,

thank you for your interest in the plugin. You are right, I need to add more information according to assigning Getters and Setters.

Firstly, according to the idea, you don't call them directly. It's the Widget calling Getters to read current values from Settings on opening\loading and the Widget calls Setters when the user presses the option buttons (slider, checkbox etc).

Secondly, Getters and Setters are assigned per each row (option) in the table. But, each row requires '**Static Context**': is the static function in a given class with no parameters that returns a living object on which Setter\Getter wants to be called.

For instance, 'GetGameUserSettings' function is static and returns 'Game User Settings' object.
![image](https://github.com/JanSeliv/SettingsWidgetConstructor/assets/20540872/ee436034-8b0f-43f1-af5e-1abdefa789e7)
![image](https://github.com/JanSeliv/SettingsWidgetConstructor/assets/20540872/b1e40819-a2db-48cb-86f5-b5b2f99c6464)
Now, Getters and Setters will be triggered for chosen functions inside 'Game User Settings' class:
![image](https://github.com/JanSeliv/SettingsWidgetConstructor/assets/20540872/54c3710a-3b48-4b21-9f43-57e3de720896)

In [Bomber](https://github.com/JanSeliv/Bomber) project you can find more examples like next:
![image](https://github.com/JanSeliv/SettingsWidgetConstructor/assets/20540872/09d8d80c-4617-4773-b7f2-3e1fdab982d5)
Where:
- 'Player Name' config property is stored in the 'My Player State' class.
- 'Static Context' sais the local 'My Player State' object can be taken from MyBlueprintFunctionLibrary::GetLocalPlayerState static function.
- Once player changed the Player Name, given Setter will called on the returned object from the 'Static Context'.
- Once player opened Settings, current value will be read and visualised on UI from returned object from the 'Static Context'

However, if you are blueprint-only user, I realized, it could be tricky or even impossible for you to prepare such static function with no code since Unreal Engine does not provide a way of creating static functions in blueprints with no parameters.
I would need to provide such support for passing 'Blueprint Function Library' function into Static Context, so blueprint-only user has a way to return a specific object containing the option. I can't say when exactly I would be able to provide such support of blueprint static contexts

**Comment by mesfeir** [comment]
ok thank you for your response and for clarifying. Yes I am mostly developing in blueprints. Please do leave a shout here, if you do implement a blueprint-way of doing this. I think having a modular widget building based on data tables is a great idea! thanks

**Comment by JanSeliv** [comment]
Hi, @mesfeir 

- Added **Blueprint Function Library** support to the latest main (UE5.3), allowing any of its blueprint functions to be used as an _Owner_ in a setting row.
- Renamed '_Static Context_' to '_Owner_' to make the naming more clear for developers.
- Added a _['Row’s Getter\Setter'](https://docs.google.com/document/d/1IXnOqrgaXTClP-0cIo28a9f6GHc9N1BCgTNnMk-X9VQ/edit#heading=h.43nc6ak4zjku)_ section to the documentation, explaining how binding works.
- Updated the [sample project](https://github.com/JanSeliv/SettingsWidgetConstructor/releases/download/vUE5.3-SampleProject/SettingsWidgetConstructorSample_UE5-3.zip) for blueprint-only developers. It demonstrates how to create and bind basic settings. As part of this example, the settings are bound to an actor that displays the player's name in the world:
<img width="640" alt="SettingsSample" src="https://github.com/JanSeliv/SettingsWidgetConstructor/assets/20540872/9bc272b1-80bf-4ed7-9eb7-90cf41438c1d">

In the next video, the creation of the sample project from scratch is shown in 10 minutes with no code involved:
https://youtu.be/FgJdTXUAGPc

Please let me know if you managed to bind the settings with the new updates.

**Comment by JanSeliv** [comment]
Closed as there are no updates so far
