### ISSUE TITLE
Plugin for UE 5.1.1

### ISSUE THREAD

**Issue by saravanan290702** [JanSeliv/SettingsWidgetConstructor#6]
Hello, is there a UE 5.1.1 release for this plugin?
Will the plugin work if i compile it in ue5.1.1...

**Comment by JanSeliv** [comment]
Hi, @saravanan290702,

Thank you for reaching out.

I do not provide backward compatibility for new features listed in the changelog for older engine versions, as other developers are selling their products on the marketplace.

However, you can find an older version of the plugin in the commit history. This version retains core functionality and is titled [Updated binaries for UE5.1](https://github.com/JanSeliv/SettingsWidgetConstructor/commit/0245c0d44ba58a3b6b63eda93780133e7cf96c6c) though it's actually for 5.1.1, so it will work and compile properly.

To access this version, simply clone the repository and revert all changes up to the specified commit (0245c0d) using the following command:
```bash
git reset --hard 0245c0d
```

Feel free to reach out if you have any more questions

**Comment by saravanan290702** [comment]
Hello i have reverted the repo to 0245c0d commit, i have yet to open it in UE 5.1.1. Just a doubt if i wanted to get the new features working in this current repo, do i just copy the all the folder expect binaries and try it out??

**Comment by JanSeliv** [comment]
Some parts of the new changes are made in the `WBP_SettingsWidgetConstructor` blueprint for newer engine versions. However, the engine does not support older versions reading blueprints saved in newer versions ([see](https://forums.unrealengine.com/t/is-there-a-way-to-migrate-assets-from-a-newer-version-of-unreal-to-an-older-build/)), so copying it won't work either. But you can try copying the `Source` folder or just parts of the code of the particular feature you are interested in, then address the compile errors in the code due to engine differences, and thereafter fix compile errors in this older blueprint.
